version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: github.com/valyala/fasthttp
    versions:
    - 1.19.0
    - 1.20.0
    - 1.21.0
  - dependency-name: go.mongodb.org/mongo-driver
    versions:
    - 1.4.5
    - 1.4.6
